name: Bug Report
description: Report a bug in the Places MCP Server
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Thanks for taking the time to report this bug!
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: "The search_places tool returns an error when searching with special characters"
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      value: |
        1. Start the MCP server
        2. Call search_places with query "café"
        3. Observe error response
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: "The search should handle special characters and return results"
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: "Server returns 400 error with message 'Invalid character in query'"
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical - System unusable
        - High - Major feature broken
        - Medium - Feature partially broken
        - Low - Minor issue
    validations:
      required: true
  - type: dropdown
    id: layer
    attributes:
      label: Affected Layer
      description: Which architecture layer is affected?
      options:
        - Configuration
        - Domain
        - Infrastructure
        - Application
        - Presentation
        - Unknown
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide environment details
      value: |
        - OS: 
        - Python version: 
        - FastMCP version: 
        - Other relevant versions:
  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please paste any relevant error logs
      render: shell
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem
      placeholder: "This started happening after upgrading to FastMCP 2.9.2"