name: Task
description: Create a development task for a user story
title: "[TASK] "
labels: ["task"]
body:
  - type: input
    id: parent
    attributes:
      label: Parent Story
      description: Link to the parent user story (e.g., #123)
      placeholder: "#"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: What specific work needs to be done?
      placeholder: "Implement the Settings model using Pydantic with validation for API keys"
    validations:
      required: true
  - type: dropdown
    id: layer
    attributes:
      label: Layer
      description: Which architecture layer does this task belong to?
      options:
        - Configuration
        - Domain
        - Infrastructure
        - Application
        - Presentation
    validations:
      required: true
  - type: input
    id: estimate
    attributes:
      label: Time Estimate (hours)
      description: How many hours will this take?
      placeholder: "4"
    validations:
      required: true
  - type: textarea
    id: implementation
    attributes:
      label: Implementation Details
      description: Technical details about how to implement this task
      placeholder: |
        - Create settings.py in config package
        - Use pydantic BaseSettings
        - Add validation for API key format
        - Support .env file loading
  - type: textarea
    id: testing
    attributes:
      label: Testing Requirements
      description: How will this task be tested?
      placeholder: |
        - Unit tests for Settings model
        - Test validation rules
        - Test environment variable loading
        - Test error cases
  - type: checkboxes
    id: checklist
    attributes:
      label: Task Checklist
      description: Standard checklist for all tasks
      options:
        - label: Implementation complete
        - label: Unit tests written
        - label: Documentation updated
        - label: Code reviewed
        - label: Integration tested